version: '3.8'

services:
  # frontend:
  #   build: ./frontend
  #   ports:
  #     - "3000:3000"
  #   environment:
  #     - NODE_ENV=development
  #   depends_on:
  #     - backend
  #   restart: unless-stopped

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development
      - MONGODB_URI=mongodb://admin:secret@mongodb:27017/mydatabase?authSource=admin
    volumes:
      - ./backend/public/uploads:/app/public/uploads 
    depends_on:
      - mongodb
    restart: unless-stopped
    networks:
    - default     
    - backend-network  # 👈 add this line

  mongodb:
    image: mongo:6
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=secret
      - MONGO_INITDB_DATABASE=mydatabase
    volumes:
      - mongodb_data:/data/db
      - ./mongodb/init:/docker-entrypoint-initdb.d:rw
    restart: unless-stopped
    networks:
      - backend-network
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh --quiet -u admin -p secret || exit 1
      interval: 5s
      timeout: 10s
      retries: 5
    entrypoint: ["/bin/bash", "-c", "chmod +x /docker-entrypoint-initdb.d/import.sh && /docker-entrypoint-initdb.d/import.sh"]

volumes:
  mongodb_data:

networks:
  backend-network:
    internal: true