version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    depends_on:
      - backend
    restart: unless-stopped


  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development
      - MONGODB_URI=mongodb://admin:secret@mongodb:27017/mydatabase?authSource=admin
    volumes:
      - ./backend/public/uploads:/app/public/uploads 
    depends_on:
      - mongodb
    restart: unless-stopped
    networks:
      - default     
      - backend-network

  mongodb:
    image: mongo:6
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=secret
      - MONGO_INITDB_DATABASE=mydatabase
    volumes:
      - mongodb_data:/data/db
    restart: unless-stopped
    networks:
      - backend-network
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh --quiet -u admin -p secret || exit 1
      interval: 15s
      timeout: 15s
      retries: 10

  mongodb-init:
    build: ./db-init
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - backend-network

volumes:
  mongodb_data:

networks:
  backend-network:
    internal: true
